name: CI/CD Pipeline
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-slim, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Build Tools (Ubuntu)
        if: matrix.os == 'ubuntu-slim'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Build Tools (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install make mingw -y

      - name: Build code
        run: |
          echo "Building the project..."
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts-${{ matrix.os }}
          path: build/test_led*
          if-no-files-found: error
  
  test:
    runs-on: ubuntu-slim
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: build-artifacts-ubuntu-slim
      
      - name: Make binary executable
        run: chmod +x test_led

      - name: Run test
        run: |
          echo "Running tests..."
          ./test_led