name: CI/CD Pipeline
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-slim]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Build Tools (Ubuntu)
        if: matrix.os == 'ubuntu-slim'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Build Tools (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install make mingw -y

      - name: Run Build System
        run: |
          echo "Building the project..."
          make

      - name: Upload Test Binary Artifact
        uses: actions/upload-artifact@v7
        with:
          name: test-binary-${{ matrix.os }}
          path: build/test*
          if-no-files-found: error
  
  test:
    runs-on: ubuntu-slim
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v7
        with:
          name: test-binary-ubuntu-slim
      
      - name: Make binary executable
        run: chmod +x test_led

      - name: Run Embedded Test Binary
        run: |
          echo "Running tests..."
          ./test*